//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RarEntities : DbContext
    {
        public RarEntities()
            : base("name=RarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Категория> Категория { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Размещение> Размещение { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<Содержимое_заказа> Содержимое_заказа { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
