//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Содержимое_заказа = new HashSet<Содержимое_заказа>();
        }
    
        public int Номер_заказа { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public string Адрес_доставки { get; set; }
        public Nullable<System.DateTime> Дата_доставки { get; set; }
        public string Доп_информация { get; set; }
        public int Код_клиента { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Содержимое_заказа> Содержимое_заказа { get; set; }
    }
}
