//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.Размещение = new HashSet<Размещение>();
            this.Содержимое_заказа = new HashSet<Содержимое_заказа>();
        }
    
        public int Код_товара { get; set; }
        public int Код_категории { get; set; }
        public string Название { get; set; }
        public decimal Цена { get; set; }
        public string Характеристики { get; set; }
        public string Производитель { get; set; }
        public string Фото { get; set; }
    
        public virtual Категория Категория { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Размещение> Размещение { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Содержимое_заказа> Содержимое_заказа { get; set; }
    }
}
